import '../../../core/app_export.dart';
import 'propertygrid_item_model.dart';

/// This class defines the variables used in the [populr_property_screen],
/// and is typically used to hold data that is passed between different parts of the application.

List<PopularPropertyListItemModel> popularPropertyListItemList = ([
  PopularPropertyListItemModel(
    image: ImageConstant.imgRectangle178581,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgBg100x100,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgRectangle178582,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgRectangle17858,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "sky Residence",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  PopularPropertyListItemModel(
    image: ImageConstant.imgRectangle178586,
    name: "New Roommate needed",
    address: "Sky Residence",
    price: "\RM200",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
]);
