import '../../../core/app_export.dart';
import 'propertygrid1_item_model.dart';

/// This class defines the variables used in the [recommended_for_you_screen],
/// and is typically used to hold data that is passed between different parts of the application.

List<RecommendedPropertyListItemModel> recommendedPropertyListItemList = ([
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgRectangle17858,
    name: "Shamelin Star",
    address: "Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "New Roommate",
    address: "Sky Residence",
    price: "\RM280",
    type: "/entry",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgRectangle178587,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgRectangle178588,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "Need roommate",
    address: "Taman ",
    price: "\RM150",
    type: "/mo",
    bed: "01",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgBg1,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgRectangle1785811,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
  RecommendedPropertyListItemModel(
    image: ImageConstant.imgRectangle1785812,
    name: "Shamelin Star",
    address: "Taman Shamelin Perkasa",
    price: "\RM400",
    type: "/mo",
    bed: "02",
    bathtub: "02",
    isFavourite: false,
  ),
]);
